### PR TITLE
 Fix autogen_envconfigs for tox 3.4.0

### LINKED ISSUE #114: Tox 3.4.0 broke tox-travis
Not sure if this is a regression in tox or if tox-travis needs to be updated.

```
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox_travis/hooks.py", line 46, in tox_configure
    autogen_envconfigs(config, undeclared)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/tox_travis/envlist.py", line 48, in autogen_envconfigs
    make_envconfig = tox.config.parseini.make_envconfig
AttributeError: module 'tox.config' has no attribute 'parseini'
```

See 
https://travis-ci.org/devpi/devpi/builds/431142175

and https://github.com/tox-dev/tox/issues/1011

### PR DESCRIPTION
**Pull request by blueyed**
Fixes #114.

### CODE REVIEW

**Comment by blueyed** [comment]
py26 generates no coverage: https://travis-ci.org/tox-dev/tox-travis/jobs/431508099#L589

File: src/tox_travis/envlist.py [hunk 1]
```diff
@@ -43,12 +45,15 @@ def autogen_envconfigs(config, envs):
     config.distshare = reader.getpath("distshare", distshare_default)
     reader.addsubstitutions(distshare=config.distshare)
 
-    # Create the undeclared envs
-    for env in envs:
+    try:
+        make_envconfig = tox.config.ParseIni.make_envconfig  # tox 3.4.0+
+    except AttributeError:
```
Comment (ryanhiebert) [inline src/tox_travis/envlist.py]: Since the try/except is what's making codecov complain, what do you think about just doing things the way of the latest version of tox, since that's what's going to be installed? Or does that not work with Python 2.6? If the latest version of tox doesn't work with Python 2.6, then I'm actually inclined to drop support for Python 2.6 in this library, rather than keep it around and worry about backward compatibility with an old version of tox. I don't think it buys us anything to keep backward compatible with old versions of tox.

Comment (blueyed) [reply src/tox_travis/envlist.py]: > Or does that not work with Python 2.6?

Yes.

I agree with dropping it.

But I also think that we can assume that the code is hit via py26 currently, although coverage reporting does not work (appears to be a problem with coverage/coverage_pth, not codecov), but not worth investigating.

As for a new release I think it's better to not necessarily require an updated tox also etc - does not really seem necessary, but it is your call.
